name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - client
      - gh-pages
  pull_request:
    branches:
      - client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install dependencies and run the build command
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Deploy to gh-pages branch
      - name: Deploy to gh-pages
        run: gh-pages -d dist -b client
